In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('default_of_credit_card_clients.xls')

In [3]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [4]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -1     -1             ...                      0          0          0   
1      0      0             ...                   3272       3455       3261   
2      0      0             ...                  14331      14948      15549   
3      0      0             ...                  28314      28959      29547   
4     -1      0             ...                  20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]

In [5]:
df['ID'].nunique()

29687

In [6]:
df['ID'].value_counts().head()

94e1b326-8c22    2
ca3910f2-92ca    2
2f4f4bc9-fd55    2
62b1d551-2414    2
d9dafe9c-b497    2
Name: ID, dtype: int64

In [7]:
df['ID'].value_counts().value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [8]:
import numpy as np

In [9]:
np.random.seed(seed=24)


In [10]:
random_integers = np.random.randint(low=1,high=5,size=100)


In [11]:
random_integers

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [12]:
is_equal_to_3 = random_integers == 3


In [13]:
is_equal_to_3[:5]


array([ True, False, False, False, False])

In [14]:
sum(is_equal_to_3)


22

In [15]:
random_integers[is_equal_to_3]


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
id_counts = df['ID'].value_counts()
dupe_mask = id_counts == 2
dupe_mask[0:5]

94e1b326-8c22    True
ca3910f2-92ca    True
2f4f4bc9-fd55    True
62b1d551-2414    True
d9dafe9c-b497    True
Name: ID, dtype: bool

In [17]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)


313

In [18]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
1899   2f4f4bc9-fd55      50000    2          2         1   44    -2     -2   
1999   2f4f4bc9-fd55          0    0          0         0    0     0      0   
12390  ca3910f2-92ca     150000    2          2         2   32     5      4   
12490  ca3910f2-92ca          0    0          0         0    0     0      0   
22527  94e1b326-8c22     120000    2          3         2   47    -1      0   
22627  94e1b326-8c22          0    0          0         0    0     0      0   

       PAY_3  PAY_4             ...              BILL_AMT4  BILL_AMT5  \
1899      -2     -2             ...                    390        390   
1999       0      0             ...                      0          0   
12390      3      2             ...                  73678      77273   
12490      0      0             ...                      0          0   
22527      0     -1             ...                    460        338   
22627      0      0             ...                      0          0   

       BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
1899           0       390       390       390       390         0       780   
1999           0         0         0         0         0         0         0   
12390      56577         0         0         0      4874      1000         0   
12490          0         0         0         0         0         0         0   
22527        679      2327      1083       500       350       700       500   
22627          0         0         0         0         0         0         0   

       default payment next month  
1899                            0  
1999                            0  
12390                           0  
12490                           0  
22527                           0  
22627                           0  

[6 rows x 25 columns]

In [19]:
df_zero_mask = df == 0


In [20]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)


315

In [21]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()


In [53]:
df_clean_1['ID'].nunique()


29685

In [54]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [55]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [56]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
PAY_1    26664 non-null int64
PAY_2    26664 non-null int64
dtypes: int64(2)
memory usage: 624.9 KB


In [24]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
4      414
Name: EDUCATION, dtype: int64

In [25]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

2    14158
1    12172
3      334
Name: MARRIAGE, dtype: int64

In [26]:
df_clean_2['EDUCATION_CAT'] = 'none'


In [27]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)


EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [28]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [29]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [32]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)
df_with_ohe.to_csv('cleaned_data.csv', index=False)
